import SplashScreen from "@/components/splash";
import ScrollProvider from "@/providers/scroll";
import type { Metadata } from "next";
import { Bebas_Neue, Space_Mono } from "next/font/google";
import "./globals.css";

const sans = Space_Mono({
  weight: "400",
  style: "normal",
  variable: "--font-sans",
  subsets: ["latin"],
});

const display = Bebas_Neue({
  weight: "400",
  style: "normal",
  variable: "--font-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sans.variable} ${display.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SplashScreen />
        <ScrollProvider>{children}</ScrollProvider>
      </body>
    </html>
  );
}
